<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \SearchHistory\Api\Representation\SearchRequestRepresentation $searchRequest
 * @var string $engine
 * @var string $query
 */

if (!$user):
    return;
endif;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$url = $plugins->get('url');
$assetUrl = $this->plugin('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/favorite.css', 'Favorite'));
$this->headScript()
    ->appendFile($assetUrl('js/favorite.js', 'Favorite'), 'text/javascript', ['defer' => 'defer']);

?>
<a class="favorite delete favorite-delete delete-favorite-button <?= $showdelbtn == 'true' ? '' : ' hidden' ?>" id="favorite_del" href="<?= $searchRequest ? $url('site/favorite-id', ['action' => 'delete', 'id' => $searchRequest->id()], true) : '' ?>"><?= sprintf($translate('Delete Favorite')) ?></a>
<a class="favorite add save-filters favorite-button <?= $showdelbtn == 'true' ? 'hidden' : ' ' ?>" id="favorite_add" data-id="<?= $resource_id ?>" href="<?= $url('site/favorite', ['action' => 'add'], true) ?>"><?= sprintf($translate('Save My Favorite')) ?></a>

